// White-hat safety filter — never suggest or enable black-hat tactics

const BLACKHAT_PATTERNS = [
  /cloaking/i,
  /doorway page/i,
  /link spam/i,
  /fake click/i,
  /fake traffic/i,
  /hidden text/i,
  /keyword stuff/i,
  /scrape google/i,
  /bypass robots/i,
  /fake review/i,
];

export function isSafeInput(input: string): boolean {
  for (const pattern of BLACKHAT_PATTERNS) {
    if (pattern.test(input)) return false;
  }
  return true;
}

export const COMPLIANCE_NOTE = `This report was generated by RankGod Local — a white-hat SEO intelligence tool. All recommendations follow Google's Webmaster Guidelines. No black-hat tactics, fake signals, or deceptive practices are suggested.`;
